el::base::utils::Utils Class Reference
Static Public Member Functions
template<typename T , typename TPtr >
static bool installCallback (const std::string &id, std::unordered_map< std::string, TPtr > *mapT)
template<typename T , typename TPtr >
static void uninstallCallback (const std::string &id, std::unordered_map< std::string, TPtr > *mapT)
template<typename T , typename TPtr >
static T * callback (const std::string &id, std::unordered_map< std::string, TPtr > *mapT)
Detailed Description
Definition at line 1531 of file easylogging++.h.
Member Function Documentation
callback()
template<typename T , typename TPtr >
static T * el::base::utils::Utils::callback (const std::string & id, std::unordered_map< std::string, TPtr > * mapT) [inline], [static]
Definition at line 1550 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::end(), and el::base::utils::RegistryWithPred< T_Ptr, Pred >::get().
installCallback()
template<typename T , typename TPtr >
static bool el::base::utils::Utils::installCallback (const std::string & id, std::unordered_map< std::string, TPtr > * mapT) [inline], [static]
Definition at line 1534 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::end().
uninstallCallback()
template<typename T , typename TPtr >
static void el::base::utils::Utils::uninstallCallback (const std::string & id, std::unordered_map< std::string, TPtr > * mapT) [inline], [static]
Definition at line 1543 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::end().
The documentation for this class was generated from the following file:
lib/easylogging++.h