json::JSONHandler Class Reference
JSONHandler class.
#include <JSONHandler.hpp>
Public Member Functions
JSONHandler (const std::string &filename)
Constructor.
std::shared_ptr< JSONData > getJSONData ()
Retrieve the JSONData object.
Private Member Functions
std::shared_ptr< Json::Value > parseFile (const std::string &filename) const
Parse a file.
void assignOutputFile () const
Assigns the output file to the JSONData object.
void assignHideShell () const
Assigns the hide shell value to the JSONData object.
void assignApplication () const
Assigns the application to the JSONData object.
void assignEntries () const
Assigns the entries to the JSONData object.
void assignCommand (const Json::Value &entry) const
Assigns a command to the JSONData object.
void assignEnvironmentVariable (const Json::Value &entry) const
Assigns an environment variable to the JSONData object.
void assignPathValue (const Json::Value &entry) const
Assigns a path value to the JSONData object.
std::shared_ptr< JSONData > createJSONData ()
Creates a JSONData object.
Private Attributes
std::shared_ptr< Json::Value > root
std::shared_ptr< JSONData > data
Detailed Description
JSONHandler class.
The JSONHandler class is responsible for parsing a json file and creating a JSONData object from it when requested. It assigns all necessary values to the JSONData object. Most of the error handling is done in the JSONData object.
Definition at line 29 of file JSONHandler.hpp.
Constructor & Destructor Documentation
JSONHandler()
json::JSONHandler::JSONHandler (const std::string & filename) [explicit]
Constructor.
The constructor calls the parseFile function to parse the file and adds it to the corresponding member variable.
Parameters
filename The filename to parse
Definition at line 9 of file JSONHandler.cpp.
References parseFile(), and root.
Member Function Documentation
assignApplication()
void json::JSONHandler::assignApplication () const [private]
Assigns the application to the JSONData object.
Note
How should error handling be done? Value can be empty, but what about null vs ""?
Definition at line 47 of file JSONHandler.cpp.
References data, and root.
assignCommand()
void json::JSONHandler::assignCommand (const Json::Value & entry) const [private]
Assigns a command to the JSONData object.
The function takes a Json::Value object and assigns the command to the JSONData object
Parameters
entry The entry to assign
Note
Error handling is done in the JSONData object
Definition at line 69 of file JSONHandler.cpp.
References data.
assignEntries()
void json::JSONHandler::assignEntries () const [private]
Assigns the entries to the JSONData object.
The function loops through the entries and calls the corresponding function to assign the entry to the JSONData object
Exceptions
std::runtime_error If the entry type is unknown
Note
Other error handling is done in the JSONData object
Definition at line 52 of file JSONHandler.cpp.
References assignCommand(), assignEnvironmentVariable(), assignPathValue(), and root.
assignEnvironmentVariable()
void json::JSONHandler::assignEnvironmentVariable (const Json::Value & entry) const [private]
Assigns an environment variable to the JSONData object.
The function takes a Json::Value object and assigns a tuple of the environment variable to the JSONData object
Parameters
entry The entry to assign
Note
Error handling is done in the JSONData object
Definition at line 74 of file JSONHandler.cpp.
References data.
assignHideShell()
void json::JSONHandler::assignHideShell () const [private]
Assigns the hide shell value to the JSONData object.
Note
There is no real error handling for this value, it defaults to false
Todo
Todo : Error handling if not found
Note
: default to false
Definition at line 40 of file JSONHandler.cpp.
References data, and root.
assignOutputFile()
void json::JSONHandler::assignOutputFile () const [private]
Assigns the output file to the JSONData object.
Note
Error handling is done in the JSONData object
Definition at line 35 of file JSONHandler.cpp.
References data, and root.
assignPathValue()
void json::JSONHandler::assignPathValue (const Json::Value & entry) const [private]
Assigns a path value to the JSONData object.
The function takes a Json::Value object and assigns the path value to the JSONData object
Parameters
entry The entry to assign
Note
Error handling is done in the JSONData object
Definition at line 80 of file JSONHandler.cpp.
References data.
createJSONData()
std::shared_ptr< JSONData > json::JSONHandler::createJSONData () [private]
Creates a JSONData object.
The function creates the JSONData object and calls all the necessary methods to assign the values to the object.
Returns
std::shared_ptr<JSONData> The JSONData object
Definition at line 26 of file JSONHandler.cpp.
References assignApplication(), assignEntries(), assignHideShell(), assignOutputFile(), and data.
getJSONData()
std::shared_ptr< JSONData > json::JSONHandler::getJSONData ()
Retrieve the JSONData object.
The function takes the necesarry steps to create a JSONData object and then returns it
Returns
std::shared_ptr<JSONData> The JSONData object
Definition at line 22 of file JSONHandler.cpp.
References createJSONData().
parseFile()
std::shared_ptr< Json::Value > json::JSONHandler::parseFile (const std::string & filename) const [private]
Parse a file.
The function takes a filename and parses the file into a Json::Value object.
Parameters
filename The filename to parse
Returns
std::shared_ptr<Json::Value> The parsed file
Definition at line 13 of file JSONHandler.cpp.
Member Data Documentation
data
std::shared_ptr<JSONData> json::JSONHandler::data [private]
Definition at line 158 of file JSONHandler.hpp.
root
std::shared_ptr<Json::Value> json::JSONHandler::root [private]
Definition at line 157 of file JSONHandler.hpp.
The documentation for this class was generated from the following files:
src/headers/JSONHandler.hpp
src/sources/JSONHandler.cpp