el::base::utils::AbstractRegistry< T_Ptr, Container > Class Template Reference
Abstract registry (aka repository) that provides basic interface for pointer repository specified by T_Ptr type.
Public Types
typedef Container::iterator iterator
typedef Container::const_iterator const_iterator
Public Member Functions
AbstractRegistry (void)
Default constructor.
AbstractRegistry (AbstractRegistry &&sr)
Move constructor that is useful for base classes.
bool operator== (const AbstractRegistry< T_Ptr, Container > &other)
bool operator!= (const AbstractRegistry< T_Ptr, Container > &other)
AbstractRegistry & operator= (AbstractRegistry &&sr)
Assignment move operator.
virtual ~AbstractRegistry (void)
virtual iterator begin (void) ELPP_FINAL
virtual iterator end (void) ELPP_FINAL
virtual const_iterator cbegin (void) const ELPP_FINAL
virtual const_iterator cend (void) const ELPP_FINAL
virtual bool empty (void) const ELPP_FINAL
virtual std::size_t size (void) const ELPP_FINAL
virtual Container & list (void) ELPP_FINAL
Returns underlying container by reference.
virtual const Container & list (void) const ELPP_FINAL
Returns underlying container by constant reference.
virtual void unregisterAll (void)=0
Unregisters all the pointers from current repository.
Public Member Functions inherited from el::base::threading::ThreadSafe
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Protected Member Functions
virtual void deepCopy (const AbstractRegistry< T_Ptr, Container > &)=0
void reinitDeepCopy (const AbstractRegistry< T_Ptr, Container > &sr)
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
Private Attributes
Container m_list
Detailed Description
template<typename T_Ptr, typename Container>
class el::base::utils::AbstractRegistry< T_Ptr, Container >
Abstract registry (aka repository) that provides basic interface for pointer repository specified by T_Ptr type.
@detail Most of the functions are virtual final methods but anything implementing this abstract class should implement unregisterAll() and deepCopy(const AbstractRegistry<T_Ptr, Container>&) and write registerNew() method according to container and few more methods; get() to find element, unregister() to unregister single entry. Please note that this is thread-unsafe and should also implement thread-safety mechanisms in implementation.
Definition at line 1255 of file easylogging++.h.
Member Typedef Documentation
const_iterator
template<typename T_Ptr , typename Container >
typedef Container::const_iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::const_iterator
Definition at line 1258 of file easylogging++.h.
iterator
template<typename T_Ptr , typename Container >
typedef Container::iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::iterator
Definition at line 1257 of file easylogging++.h.
Constructor & Destructor Documentation
AbstractRegistry() [1/2]
template<typename T_Ptr , typename Container >
el::base::utils::AbstractRegistry< T_Ptr, Container >::AbstractRegistry (void) [inline]
Default constructor.
Definition at line 1261 of file easylogging++.h.
AbstractRegistry() [2/2]
template<typename T_Ptr , typename Container >
el::base::utils::AbstractRegistry< T_Ptr, Container >::AbstractRegistry (AbstractRegistry< T_Ptr, Container > && sr) [inline]
Move constructor that is useful for base classes.
Definition at line 1264 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::m_list.
~AbstractRegistry()
template<typename T_Ptr , typename Container >
virtual el::base::utils::AbstractRegistry< T_Ptr, Container >::~AbstractRegistry (void) [inline], [virtual]
Definition at line 1306 of file easylogging++.h.
Member Function Documentation
begin()
template<typename T_Ptr , typename Container >
virtual iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::begin (void) [inline], [virtual]
Returns
Iterator pointer from start of repository
Definition at line 1310 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::begin().
cbegin()
template<typename T_Ptr , typename Container >
virtual const_iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::cbegin (void) const [inline], [virtual]
Returns
Constant iterator pointer from start of repository
Definition at line 1321 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::cbegin().
cend()
template<typename T_Ptr , typename Container >
virtual const_iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::cend (void) const [inline], [virtual]
Returns
End of repository
Definition at line 1326 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::cend().
deepCopy()
template<typename T_Ptr , typename Container >
virtual void el::base::utils::AbstractRegistry< T_Ptr, Container >::deepCopy (const AbstractRegistry< T_Ptr, Container > &) [protected], [pure virtual]
Implemented in el::base::utils::RegistryWithPred< T_Ptr, Pred >.
empty()
template<typename T_Ptr , typename Container >
virtual bool el::base::utils::AbstractRegistry< T_Ptr, Container >::empty (void) const [inline], [virtual]
Returns
Whether or not repository is empty
Definition at line 1331 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::empty().
end()
template<typename T_Ptr , typename Container >
virtual iterator el::base::utils::AbstractRegistry< T_Ptr, Container >::end (void) [inline], [virtual]
Returns
Iterator pointer from end of repository
Definition at line 1315 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::end().
list() [1/2]
template<typename T_Ptr , typename Container >
virtual const Container & el::base::utils::AbstractRegistry< T_Ptr, Container >::list (void) const [inline], [virtual]
Returns underlying container by constant reference.
Definition at line 1346 of file easylogging++.h.
list() [2/2]
template<typename T_Ptr , typename Container >
virtual Container & el::base::utils::AbstractRegistry< T_Ptr, Container >::list (void) [inline], [virtual]
Returns underlying container by reference.
Definition at line 1341 of file easylogging++.h.
operator!=()
template<typename T_Ptr , typename Container >
bool el::base::utils::AbstractRegistry< T_Ptr, Container >::operator!= (const AbstractRegistry< T_Ptr, Container > & other) [inline]
Definition at line 1284 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::m_list, and el::base::utils::AbstractRegistry< T_Ptr, Container >::size().
operator=()
template<typename T_Ptr , typename Container >
AbstractRegistry & el::base::utils::AbstractRegistry< T_Ptr, Container >::operator= (AbstractRegistry< T_Ptr, Container > && sr) [inline]
Assignment move operator.
Definition at line 1297 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::m_list.
operator==()
template<typename T_Ptr , typename Container >
bool el::base::utils::AbstractRegistry< T_Ptr, Container >::operator== (const AbstractRegistry< T_Ptr, Container > & other) [inline]
Definition at line 1272 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::m_list, and el::base::utils::AbstractRegistry< T_Ptr, Container >::size().
reinitDeepCopy()
template<typename T_Ptr , typename Container >
void el::base::utils::AbstractRegistry< T_Ptr, Container >::reinitDeepCopy (const AbstractRegistry< T_Ptr, Container > & sr) [inline], [protected]
Definition at line 1355 of file easylogging++.h.
size()
template<typename T_Ptr , typename Container >
virtual std::size_t el::base::utils::AbstractRegistry< T_Ptr, Container >::size (void) const [inline], [virtual]
Returns
Size of repository
Definition at line 1336 of file easylogging++.h.
References el::base::utils::AbstractRegistry< T_Ptr, Container >::size().
unregisterAll()
template<typename T_Ptr , typename Container >
virtual void el::base::utils::AbstractRegistry< T_Ptr, Container >::unregisterAll (void) [pure virtual]
Unregisters all the pointers from current repository.
Implemented in el::base::utils::Registry< T_Ptr, T_Key >, el::base::utils::Registry< Logger, std::string >, el::base::utils::RegistryWithPred< T_Ptr, Pred >, el::base::utils::RegistryWithPred< base::HitCounter, base::HitCounter::Predicate >, and el::base::utils::RegistryWithPred< Configuration, Configuration::Predicate >.
Field Documentation
m_list
template<typename T_Ptr , typename Container >
Container el::base::utils::AbstractRegistry< T_Ptr, Container >::m_list [private]
Definition at line 1361 of file easylogging++.h.
The documentation for this class was generated from the following file:
lib/easylogging++.h