el::base::DefaultLogDispatchCallback Class Reference
Protected Member Functions
void handle (const LogDispatchData *data)
Protected Member Functions inherited from el::LogDispatchCallback
base::threading::Mutex & fileHandle (const LogDispatchData *data)
Protected Member Functions inherited from el::base::threading::ThreadSafe
ThreadSafe (void)
virtual ~ThreadSafe (void)
virtual void acquireLock (void) ELPP_FINAL
virtual void releaseLock (void) ELPP_FINAL
virtual base::threading::Mutex & lock (void) ELPP_FINAL
Private Member Functions
void dispatch (base::type::string_t &&logLine)
Private Attributes
const LogDispatchData * m_data
Additional Inherited Members
Public Member Functions inherited from el::Callback< LogDispatchData >
Callback (void)
bool enabled (void) const
void setEnabled (bool enabled)
Detailed Description
Definition at line 2726 of file easylogging++.h.
Member Function Documentation
dispatch()
void el::base::DefaultLogDispatchCallback::dispatch (base::type::string_t && logLine) [private]
Definition at line 2215 of file easylogging++.cc.
References el::ColoredTerminalOutput, el::LogBuilder::convertToColoredOutput(), el::LevelHelper::convertToString(), el::Debug, el::LogDispatchData::dispatchAction(), ELPP, ELPP_COUT, ELPP_COUT_LINE, ELPP_INTERNAL_ERROR, el::Error, el::Fatal, el::base::TypedConfigurations::filename(), el::base::TypedConfigurations::fileStream(), el::Logger::flush(), el::Logger::id(), el::ImmediateFlush, el::Info, el::Logger::isFlushNeeded(), el::LogMessage::level(), el::Logger::logBuilder(), el::LogMessage::logger(), el::LogDispatchData::logMessage(), m_data, el::Logger::m_typedConfigurations, el::base::NormalLog, el::base::SysLog, el::base::TypedConfigurations::toFile(), el::base::TypedConfigurations::toStandardOutput(), el::Warning, and el::base::utils::Str::wcharPtrToCharPtr().
handle()
void el::base::DefaultLogDispatchCallback::handle (const LogDispatchData * data) [protected], [virtual]
Reimplemented from el::LogDispatchCallback.
Definition at line 2205 of file easylogging++.cc.
References el::LogBuilder::build(), dispatch(), el::LogDispatchData::dispatchAction(), el::LogDispatchCallback::fileHandle(), el::LogDispatchCallback::handle(), el::Logger::logBuilder(), el::LogMessage::logger(), el::LogDispatchData::logMessage(), m_data, and el::base::NormalLog.
Field Documentation
m_data
const LogDispatchData* el::base::DefaultLogDispatchCallback::m_data [private]
Definition at line 2730 of file easylogging++.h.
The documentation for this class was generated from the following files:
lib/easylogging++.h
lib/easylogging++.cc