el::base::utils::OS Class Reference
Operating System helper static class used internally. You should not use it.
Static Public Member Functions
static const std::string getBashOutput (const char *command)
Runs command on terminal and returns the output.
static std::string getEnvironmentVariable (const char *variableName, const char *defaultVal, const char *alternativeBashCommand=nullptr)
Gets environment variable. This is cross-platform and CRT safe (for VC++)
static std::string currentUser (void)
Gets current username.
static std::string currentHost (void)
Gets current host name or computer name.
static bool termSupportsColor (void)
Whether or not terminal supports colors.
Detailed Description
Operating System helper static class used internally. You should not use it.
Definition at line 1137 of file easylogging++.h.
Member Function Documentation
currentHost()
std::string el::base::utils::OS::currentHost (void) [static]
Gets current host name or computer name.
@detail For android systems this is device name with its manufacturer and model separated by hyphen
Definition at line 1128 of file easylogging++.cc.
References ELPP_UNUSED, getEnvironmentVariable(), and el::base::consts::kUnknownHost.
currentUser()
std::string el::base::utils::OS::currentUser (void) [static]
Gets current username.
Definition at line 1115 of file easylogging++.cc.
References ELPP_UNUSED, getEnvironmentVariable(), and el::base::consts::kUnknownUser.
getBashOutput()
const std::string el::base::utils::OS::getBashOutput (const char * command) [static]
Runs command on terminal and returns the output.
@detail This is applicable only on unix based systems, for all other OS, an empty string is returned.
Parameters
command Bash command
Returns
Result of bash output or empty string if no result found.
Definition at line 1063 of file easylogging++.cc.
References ELPP_INTERNAL_ERROR, and ELPP_UNUSED.
getEnvironmentVariable()
std::string el::base::utils::OS::getEnvironmentVariable (const char * variableName, const char * defaultVal, const char * alternativeBashCommand = nullptr) [static]
Gets environment variable. This is cross-platform and CRT safe (for VC++)
Parameters
variableName Environment variable name
defaultVal If no environment variable or value found the value to return by default
alternativeBashCommand If environment variable not found what would be alternative bash command in order to look for value user is looking for. E.g, for 'user' alternative command will 'whoami'
Definition at line 1091 of file easylogging++.cc.
References ELPP_UNUSED, and getBashOutput().
termSupportsColor()
bool el::base::utils::OS::termSupportsColor (void) [static]
Whether or not terminal supports colors.
Definition at line 1141 of file easylogging++.cc.
References getEnvironmentVariable().
The documentation for this class was generated from the following files:
include/easylogging++.h
lib/easylogging++.cc