src/main.cpp File Reference
#include "BatchCreator.hpp"
#include "CliHandler.hpp"
#include "JSONData.hpp"
#include "JSONHandler.hpp"
#include "LogAndOut.hpp"
#include "StartupHandler.hpp"
#include <easylogging++.h>
#include <filesystem>
#include <getopt.h>
#include <iostream>
#include <json/json.h>
#include <stdexcept>
#include <string>
Macros
#define FL std::flush
Functions
INITIALIZE_EASYLOGGINGPP int main (int argc, char *argv[])
Main function.
Macro Definition Documentation
FL
#define FL std::flush
Note
Temporary till logger is fixed
Definition at line 17 of file main.cpp.
Function Documentation
main()
INITIALIZE_EASYLOGGINGPP int main (int argc, char * argv[])
Main function.
Bug
Bug Initielizes to early for config file to be loaded
This is the main function for the application, The application is designed to parse a json file and create a batch file from it. Further more it provides a CLI to help the user to interact with the application.
Bug
Bug Getopt is not working on Windows.
Note
maybe close in creator? But this leaves possibility to add more stuff - why?
Definition at line 34 of file main.cpp.
References cli::CLEAR_TERMINAL, batch::BatchCreator::createBatchFile(), json::JSONHandler::getJSONData(), utils::StartupHandler::getOptions(), cli::GREEN_FG, utils::StartupHandler::initEasyLogging(), cli::ITALIC, LOG_ERROR, LOG_INFO, LOG_WARNING, OUTPUT, cli::RESET, and cli::UNDERLINE.