el::base::utils Namespace Reference
Namespace containing utility functions/static classes used internally.
Namespaces
namespace bitwise
Bitwise operations for C++11 strong enum class. This casts e into Flag_T and returns value after bitwise operation Use these function as.
Data Structures
class AbstractRegistry
Abstract registry (aka repository) that provides basic interface for pointer repository specified by T_Ptr type.
class CommandLineArgs
Command line arguments for application if specified using el::Helpers::setArgs(..) or START_EASYLOGGINGPP(..)
class DateTime
Contains utilities for cross-platform date/time. This class make use of el::base::utils::Str.
class File
class OS
Operating System helper static class used internally. You should not use it.
class Registry
A pointer registry mechanism to manage memory and provide search functionalities. (non-predicate version)
class RegistryWithPred
A pointer registry mechanism to manage memory and provide search functionalities. (predicate version)
class Str
String utilities helper class used internally. You should not use it.
class Utils
Functions
template<typename T >
static std::enable_if< std::is_pointer< T * >::value, void >::type safeDelete (T *&pointer)
Deletes memory safely and points to null.
template<typename Enum >
static void addFlag (Enum e, base::type::EnumType *flag)
template<typename Enum >
static void removeFlag (Enum e, base::type::EnumType *flag)
template<typename Enum >
static bool hasFlag (Enum e, base::type::EnumType flag)
static void abort (int status, const std::string &reason)
Aborts application due with user-defined status.
base::type::ostream_t & operator<< (base::type::ostream_t &os, const CommandLineArgs &c)
Detailed Description
Namespace containing utility functions/static classes used internally.
Function Documentation
abort()
static void el::base::utils::abort (int status, const std::string & reason) [static]
Aborts application due with user-defined status.
Definition at line 113 of file easylogging++.cc.
References abort(), and ELPP_UNUSED.
addFlag()
template<typename Enum >
static void el::base::utils::addFlag (Enum e, base::type::EnumType * flag) [inline], [static], [private]
Definition at line 881 of file easylogging++.h.
References el::base::utils::bitwise::Or().
hasFlag()
template<typename Enum >
static bool el::base::utils::hasFlag (Enum e, base::type::EnumType flag) [inline], [static], [private]
Definition at line 889 of file easylogging++.h.
References el::base::utils::bitwise::Or().
operator<<()
base::type::ostream_t & el::base::utils::operator<< (base::type::ostream_t & os, const CommandLineArgs & c)
Definition at line 1368 of file easylogging++.cc.
removeFlag()
template<typename Enum >
static void el::base::utils::removeFlag (Enum e, base::type::EnumType * flag) [inline], [static], [private]
Definition at line 885 of file easylogging++.h.
References el::base::utils::bitwise::Or().
safeDelete()
template<typename T >
static std::enable_if< std::is_pointer< T * >::value, void >::type el::base::utils::safeDelete (T *& pointer) [static], [private]
Deletes memory safely and points to null.
Definition at line 858 of file easylogging++.h.