Json Namespace Reference
JSON (JavaScript Object Notation).
Data Structures
class CharReader
class CharReaderBuilder
Build a CharReader implementation.
class Exception
class FastWriter
Outputs a Value in JSON format without formatting (not human friendly).
class Features
Configuration passed to reader and writer. This configuration object can be used to force the Reader or Writer to behave in a standard conforming way.
class LogicError
class Path
Experimental and untested: represents a "path" to access a node.
class PathArgument
Experimental and untested: represents an element of the "path" to access a node.
class Reader
Unserialize a JSON document into a Value.
class RuntimeError
class SecureAllocator
class StaticString
Lightweight wrapper to tag static string.
class StreamWriter
class StreamWriterBuilder
Build a StreamWriter implementation.
class StyledStreamWriter
Writes a Value in JSON format in a human friendly way, to a stream rather than to a string.
class StyledWriter
Writes a Value in JSON format in a human friendly way.
class Value
Represents a JSON value.
class ValueConstIterator
const iterator for object and array value.
class ValueIterator
Iterator for object and array value.
class ValueIteratorBase
base class for Value iterators.
class Writer
Abstract class for writers.
Typedefs
using Int = int
using UInt = unsigned int
using Int64 = int64_t
using UInt64 = uint64_t
using LargestInt = Int64
using LargestUInt = UInt64
template<typename T >
using Allocator = typename std::conditional< JSONCPP_USING_SECURE_MEMORY, SecureAllocator< T >, std::allocator< T > >::type
using String = std::basic_string< char, std::char_traits< char >, Allocator< char > >
using IStringStream = std::basic_istringstream< String::value_type, String::traits_type, String::allocator_type >
using OStringStream = std::basic_ostringstream< String::value_type, String::traits_type, String::allocator_type >
using IStream = std::istream
using OStream = std::ostream
using ArrayIndex = unsigned int
Enumerations
enum ValueType {
nullValue = 0
, intValue
, uintValue
, realValue
,
stringValue
, booleanValue
, arrayValue
, objectValue
 }
Type of the value held by a Value object.
enum CommentPlacement { commentBefore = 0
, commentAfterOnSameLine
, commentAfter
, numberOfCommentPlacement
 }
enum PrecisionType { significantDigits = 0
, decimalPlaces
 }
Type of precision for formatting of real values.
Functions
template<typename T , typename U >
bool operator== (const SecureAllocator< T > &, const SecureAllocator< U > &)
template<typename T , typename U >
bool operator!= (const SecureAllocator< T > &, const SecureAllocator< U > &)
bool JSON_API parseFromStream (CharReader::Factory const &, IStream &, Value *root, String *errs)
JSON_API IStream & operator>> (IStream &, Value &)
Read from 'sin' into 'root'.
JSONCPP_NORETURN void throwRuntimeError (String const &msg)
used internally
JSONCPP_NORETURN void throwLogicError (String const &msg)
used internally
void swap (Value &a, Value &b)
String JSON_API writeString (StreamWriter::Factory const &factory, Value const &root)
Write into stringstream, then return string, for convenience. A StreamWriter will be created from the factory, used, and then deleted.
String JSON_API valueToString (Int value)
String JSON_API valueToString (UInt value)
String JSON_API valueToString (LargestInt value)
String JSON_API valueToString (LargestUInt value)
String JSON_API valueToString (double value, unsigned int precision=Value::defaultRealPrecision, PrecisionType precisionType=PrecisionType::significantDigits)
String JSON_API valueToString (bool value)
String JSON_API valueToQuotedString (const char *value)
JSON_API OStream & operator<< (OStream &, const Value &root)
Output using the StyledStreamWriter.
Detailed Description
JSON (JavaScript Object Notation).
Typedef Documentation
Allocator
template<typename T >
using Json::Allocator = typedef typename std::conditional<JSONCPP_USING_SECURE_MEMORY, SecureAllocator<T>, std::allocator<T> >::type
Definition at line 129 of file config.h.
ArrayIndex
using Json::ArrayIndex = typedef unsigned int
Definition at line 32 of file forwards.h.
Int
using Json::Int = typedef int
Definition at line 108 of file config.h.
Int64
using Json::Int64 = typedef int64_t
Definition at line 120 of file config.h.
IStream
using Json::IStream = typedef std::istream
Definition at line 139 of file config.h.
IStringStream
using Json::IStringStream = typedef std::basic_istringstream<String::value_type, String::traits_type, String::allocator_type>
Definition at line 133 of file config.h.
LargestInt
using Json::LargestInt = typedef Int64
Definition at line 123 of file config.h.
LargestUInt
using Json::LargestUInt = typedef UInt64
Definition at line 124 of file config.h.
OStream
using Json::OStream = typedef std::ostream
Definition at line 140 of file config.h.
OStringStream
using Json::OStringStream = typedef std::basic_ostringstream<String::value_type, String::traits_type, String::allocator_type>
Definition at line 136 of file config.h.
String
using Json::String = typedef std::basic_string<char, std::char_traits<char>, Allocator<char> >
Definition at line 132 of file config.h.
UInt
using Json::UInt = typedef unsigned int
Definition at line 109 of file config.h.
UInt64
using Json::UInt64 = typedef uint64_t
Definition at line 121 of file config.h.
Enumeration Type Documentation
CommentPlacement
enum Json::CommentPlacement
Enumerator
commentBefore a comment placed on the line before a value
commentAfterOnSameLine a comment just after a value on the same line
commentAfter a comment on the line after a value (only make sense for
numberOfCommentPlacement root value)
Definition at line 119 of file value.h.
PrecisionType
enum Json::PrecisionType
Type of precision for formatting of real values.
Enumerator
significantDigits we set max number of significant digits in string
decimalPlaces we set max number of digits after "." in string
Definition at line 129 of file value.h.
ValueType
enum Json::ValueType
Type of the value held by a Value object.
Enumerator
nullValue 'null' value
intValue signed integer value
uintValue unsigned integer value
realValue double value
stringValue UTF-8 string value.
booleanValue bool value
arrayValue array value (ordered list)
objectValue object value (collection of name/value pairs).
Definition at line 108 of file value.h.
Function Documentation
operator!=()
template<typename T , typename U >
bool Json::operator!= (const SecureAllocator< T > & , const SecureAllocator< U > &)
Definition at line 89 of file allocator.h.
operator<<()
JSON_API OStream & Json::operator<< (OStream & , const Value & root)
Output using the StyledStreamWriter.
See also
Json::operator>>()
operator==()
template<typename T , typename U >
bool Json::operator== (const SecureAllocator< T > & , const SecureAllocator< U > &)
Definition at line 84 of file allocator.h.
operator>>()
JSON_API IStream & Json::operator>> (IStream & , Value &)
Read from 'sin' into 'root'.
Always keep comments from the input JSON.
This can be used to read a file into a particular sub-object. For example:
Json::Value root;
cin >> root["dir"]["file"];
cout << root;
 Result:
* {
* "dir": {
*    "file": {
*    // The input stream JSON would be nested here.
*    }
* }
* }
* 
Exceptions
std::exception on parse error.
See also
Json::operator<<()
parseFromStream()
bool JSON_API Json::parseFromStream (CharReader::Factory const & , IStream & , Value * root, String * errs)
Consume entire stream and use its begin/end. Someday we might have a real StreamReader, but for now this is convenient.
swap()
void Json::swap (Value & a, Value & b) [inline]
Definition at line 992 of file value.h.
References swap(), and Json::Value::swap().
throwLogicError()
JSONCPP_NORETURN void Json::throwLogicError (String const & msg)
used internally
References throwLogicError().
throwRuntimeError()
JSONCPP_NORETURN void Json::throwRuntimeError (String const & msg)
used internally
References throwRuntimeError().
valueToQuotedString()
String JSON_API Json::valueToQuotedString (const char * value)
valueToString() [1/6]
String JSON_API Json::valueToString (bool value)
valueToString() [2/6]
String JSON_API Json::valueToString (double value, unsigned int precision = Value::defaultRealPrecision, PrecisionType precisionType = PrecisionType::significantDigits)
valueToString() [3/6]
String JSON_API Json::valueToString (Int value)
valueToString() [4/6]
String JSON_API Json::valueToString (LargestInt value)
valueToString() [5/6]
String JSON_API Json::valueToString (LargestUInt value)
valueToString() [6/6]
String JSON_API Json::valueToString (UInt value)
writeString()
String JSON_API Json::writeString (StreamWriter::Factory const & factory, Value const & root)
Write into stringstream, then return string, for convenience. A StreamWriter will be created from the factory, used, and then deleted.