.TH "src/headers Directory Reference" 3 "Wed Feb 28 2024 22:07:52" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBatchCreator\&.hpp\fP"
.br
.ti -1c
.RI "file \fBCliHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBJSONData\&.hpp\fP"
.br
.ti -1c
.RI "file \fBJSONHandler\&.hpp\fP"
.br
.ti -1c
.RI "file \fBStartupHandler\&.hpp\fP"
.br
.in -1c
