.TH "src/sources Directory Reference" 3 "Wed Feb 28 2024 22:07:52" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBatchCreator\&.cpp\fP"
.br
.ti -1c
.RI "file \fBCliHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBJSONData\&.cpp\fP"
.br
.ti -1c
.RI "file \fBJSONHandler\&.cpp\fP"
.br
.ti -1c
.RI "file \fBStartupHandler\&.cpp\fP"
.br
.in -1c
