.TH "src/headers/BatchCreator.hpp" 3 "Wed Feb 28 2024 22:07:52" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers/BatchCreator.hpp
.SH SYNOPSIS
.br
.PP
\fC#include 'JSONData\&.hpp'\fP
.br
\fC#include <memory>\fP
.br
\fC#include <fstream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBbatch::BatchCreator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBbatch\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
