.TH "batch" 3 "Thu Feb 29 2024 12:13:30" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
batch
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBatchCreator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
