.TH "src/sources/BatchCreator.cpp" 3 "Wed Feb 28 2024 22:07:52" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources/BatchCreator.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'BatchCreator\&.hpp'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <utility>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
