.TH "bug" 3 "Thu Feb 29 2024 12:13:30" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
.PP

.IP "\fBClass \fBbatch::BatchCreator\fP \fP" 1c
HideShell is not implemented correctly  
.IP "\fBNamespace \fBjson\fP \fP" 1c
 Name to similiar to 'Json' namespace from the json library\&.  
.IP "\fBMember \fBmain\fP (int argc, char *argv[])\fP" 1c
Initielizes to early for config file to be loaded 
.PP
Getopt is not working on Windows\&.  
.IP "\fBMember \fButils::StartupHandler::getOptions\fP (int argc, char *argv[])\fP" 1c
 Global verbose flag is not working\&. 
.IP "\fBMember \fButils::StartupHandler::initEasyLogging\fP ()\fP" 1c
 Easylogging conf only recognized when running application from source dir 
.PP

