.TH "clInterface::CliHandler" 3 "Wed Feb 28 2024 22:07:52" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
clInterface::CliHandler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <CliHandler\&.hpp>\fP
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBCliHandler\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
