.TH "src/sources/JSONData.cpp" 3 "Wed Feb 28 2024 22:07:52" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/sources/JSONData.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'JSONData\&.hpp'\fP
.br
\fC#include <easylogging++\&.h>\fP
.br
\fC#include <ostream>\fP
.br
\fC#include <stdexcept>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBjson\fP"
.br
.RI "json namespace "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
