.TH "json" 3 "Wed Feb 28 2024 22:07:52" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
json \- json namespace  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBJSONData\fP"
.br
.ti -1c
.RI "class \fBJSONHandler\fP"
.br
.RI "\fBJSONHandler\fP class\&. "
.in -1c
.SH "Detailed Description"
.PP 
json namespace 

The json namespace contains all classes and functions related to the json parsing and handling\&.
.PP
\fBBug\fP
.RS 4
Name to similiar to 'Json' namespace from the json library\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
