.TH "src/headers/StartupHandler.hpp" 3 "Wed Feb 28 2024 08:49:55" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers/StartupHandler.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <getopt\&.h>\fP
.br
\fC#include <optional>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fButils::StartupHandler\fP"
.br
.RI "Handles startup task for the application\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButils\fP"
.br
.RI "Namespace for utility functions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
