.TH "src/headers/Verbose.hpp" 3 "Thu Feb 29 2024 12:13:30" "Version 0.2.0" "jsonToBatProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/headers/Verbose.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <optional>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fButils::VerboseHandler\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fButils\fP"
.br
.RI "Namespace for utility functions\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for jsonToBatProject from the source code\&.
