# This is a basic workflow to help you get started with Actions

name: "Doxygen Action"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.9.8
